# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple Linear Regression function with Rcpp
#' @name SLM
#' @param x A size n predictor vector
#' @param y A size n outcome vector
#' @returns A list containing: intercept, beta estimate, std.Error, t.value, p.value from the simple linear regression
#' @export
NULL

SLM <- function(x, y) {
    .Call(`_LM_SLM`, x, y)
}

